name: sbti_getting_started
channels:
  - conda-forge
  - defaults
dependencies:
  - git=2.28.0=0
  - pip=23.2.1
  - python=3.10.12
  - jupyter=4.0.5
  - pip:
    - git+git://github.com/WWF_Sweden/ITR-tool 
    - WWF-finance-tool 
    - -r requirements.txt