name: ITR_getting_started
channels:
  - conda-forge
  - defaults
dependencies:
  - git=2.28.0=0
  - pip=20.2.1=py_0
  - python>=3.9.7
  - jupyter=1.0.0=py_2
  - pip:
    - git+https://github.com/WWF-Sweden/ITR-tool
