name: ITR_getting_started
channels:
  - conda-forge
  - defaults
dependencies:
  - git>=2.28
  - pip>=20.2
  - python>=3.10
  - jupyter>=1.0.0
  - pip:
    - git+https://github.com/WWF-Sweden/ITR-tool
